### ISSUE TITLE
variable name wrong if model contains only 1 covariate

### ISSUE THREAD

**Issue by philippbroniecki** [altaf-ali/regsim#25]
The following code illustrates the problem

`library(regsim)`
`com <- read.csv("http://philippbroniecki.github.io/ML2017.io/data/communities.csv")`
`m1 <- lm(PctUnemployed ~ PctNotHSGrad, com)`
`x <- list(PctNotHSGrad = seq(0,1,.1))`
`sim <- regsim(m1, x)`
`# does not work`
`plot(sim, ~ PctNotHSGrad)`
`# does work`
`plot(sim, ~ x)`

**Comment by altaf-ali** [comment]
are you sure about this? it works fine for me.

> library(regsim)
> com <- read.csv("http://philippbroniecki.github.io/ML2017.io/data/communities.csv")
> m1 <- lm(PctUnemployed ~ PctNotHSGrad, com)
> x <- list(PctNotHSGrad = seq(0,1,.1))
> sim <- regsim(m1, x)
> plot(sim, ~ PctNotHSGrad)
> plot(sim, ~ x)
Error in plot.regsim(sim, ~x) : x not in the model
> packageVersion("regsim")
[1] ‘0.1.6’

**Comment by philippbroniecki** [comment]
You're right. My version was old. Sorry about that!
