### ISSUE TITLE
regsim does not work with poly() function

### ISSUE THREAD

**Issue by philippbroniecki** [altaf-ali/regsim#32]
This code leads to the error:
`library(regsim)`
`world_data <- read.csv("QoG2012.csv")`
`world_data <- world_data[apply(apply(world_data[,c("wdi_gdpc","undp_hdi","wbgi_pse")], 2, function(x) (!is.na(x)) ),1,all),]`
`m <- lm( undp_hdi ~ poly(wdi_gdpc,2) + former_col, data = world_data)`
`x <- list(wdi_gdpc = seq(from = 0, to = 60000, by = 1000))`
`sim <- regsim_common(m, x)`

That's my fix:

`function(object, x, num = 1000, link = NULL) {`
`  formula_rhs_terms <- attr(stats::terms(stats::formula(object)), "term.labels")`

`  # poly option`
`  a.poly <- grepl("poly", formula_rhs_terms)`
`  if (length(a.poly)) a.poly <- which(a.poly)`
`  if(length(unknown_vars)){`
`    if(grepl(unknown_vars[a.poly], formula_rhs_terms[a.poly]) & grepl("poly", formula_rhs_terms[a.poly])){`
`      if (length(unknown_vars)==1) unknown_vars <- NULL`
`      if (length(unknown_vars)>1) unknown_vars <- unknown_vars[-a.poly]`
`      }`
`  }`

`  # check explanatory variables given to us`
`  unknown_vars <- setdiff(names(x), formula_rhs_terms)`

`  if (length(unknown_vars))`
`    stop(paste(paste(unknown_vars, collapse = ", "), "not in the model"))`

What do you think?

**Comment by altaf-ali** [comment]
fixed in release 0.1.9 by pr #34
