### ISSUE TITLE
sometimes the plot function creates a legend that is too big

### ISSUE THREAD

**Issue by altaf-ali** [altaf-ali/regsim#5]
need to add code to reproduce the problem

**Comment by philippbroniecki** [comment]
`rm(list = ls())`
`library(regsim)`
`df <- read.csv("http://philippbroniecki.github.io/ML2017.io/data/communities.csv")`

### run model
`df$big <- NA`
`df$big <- ifelse(df$population > .02, 1, 0)`
`m1 <- lm(PctUnemployed ~ pctUrban + householdsize * racePctWhite + big, data = df)`

### set covariates
`x <- list(householdsize = mean(df$householdsize),
racePctWhite = seq(0,1, by = .1),
big = 0:1)`

### simulate
`sim <- regsim(m1, x, 1000)`

### plotting
`plot(x = sim, var = ~racePctWhite+big, ylim = c(0,1), bty = "n")`

**Comment by altaf-ali** [comment]
I think the legend is always too big. It looks ok in markdown but too ugly when you zoom in rstudio. Same thing happens even with this plot, which otherwise looks ok in markdown: https://altaf-ali.github.io/regsim/articles/interaction_terms.html

I'll take a look at it later. Last resort would be to allow the user to override legend arguments but I'd rather not add more options yet.

**Comment by philippbroniecki** [comment]
it might be good to set bg = "transparent" in legend so that at the very least we can see the lines.

works a little better usually, I think but not a great solution.
``
graphics::legend("bottomright",
                     y = NULL,
                     groups,
                     inset = .02,
                     title = zvar,
                     fill = color_map,
                     cex = 1,
                     y.intersp = 0.55,
                     x.intersp = 0.25,
                     bty = "n",
                     bg = "transparent",
                     horiz = TRUE)
``

**Comment by altaf-ali** [comment]
Now the legend is messed up in markdown :(

![unnamed-chunk-6-1](https://user-images.githubusercontent.com/7231912/29915807-dc5686ea-8e34-11e7-8599-f5bc5bfd91e7.png)

**Comment by altaf-ali** [comment]
But I've a fix that changes some of the legend defaults. I've changed it so the legend seems reasonable in both markdown and interactive modes. If someone doesn't like these defaults, then they can override them. Here's a tricky little syntax to do that:

For each layer of the plot, you can override the arguments using a prefix of "lines", "polygon", or "legend" and the arguments will be dispatched to the appropriate lines, polygons or legend function. For example, "lines.col", "polygon.col", "legend.title", etc. 

plot(sim, ~ wt, 
     xlab = "Weight",        # general plot argument
     polygon.col = "Dark2",  # change polygon palette from color brewer 
     lines.col = "blue",     # lines color
     legend.x = "bottomleft" # legend position
  )

**Comment by altaf-ali** [comment]
Confirmed fixed. Now the plot from the original example above looks like this:

![rplot](https://user-images.githubusercontent.com/7231912/29917045-93a10624-8e38-11e7-8511-d8a08052a3c6.png)
